"""
AutoGen Integration Module for AI PC Diagnostic Agent

This module integrates Microsoft AutoGen to automate execution of MCP tasks
generated by the AI diagnostic model.
"""

from .orchestrator import AutoGenOrchestrator
from .parsers.mcp_parser import MCPTaskParser

__all__ = ['AutoGenOrchestrator', 'MCPTaskParser']
