# Generated by Django 5.2.6 on 2025-10-31 15:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['-updated_at'], name='ai_diagnost_updated_107e76_idx'), models.Index(fields=['is_archived'], name='ai_diagnost_is_arch_4ca0cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('issue_category', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution_status', models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved'), ('in_progress', 'In Progress')], default='unresolved', max_length=50)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='ai_diagnostic.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('finish_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_diagnostic.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['conversation', 'timestamp'], name='ai_diagnost_convers_529404_idx')],
            },
        ),
    ]
